#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
#pragma config(Sensor, S3,     irSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorC,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorB,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorA,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	 int x;

	 while(true)
	 {
	   x=SensorValue[irSeeker];
	   x=x+0;

	   if (x == 5)
	   {
	     motor[motorA] = -50;                //Motor C is run at a 100 power level
      motor[motorB] = 50;                //motor B is run at a 100 power level
      motor[motorC] = -50;
      motor[motorD] = 50;
      wait1Msec(600);

      motor[motorA] = 0;                //Motor C is run at a 100 power level
      motor[motorB] = 0;                //motor B is run at a 100 power level
      motor[motorC] = 0;
      motor[motorD] = 0;
      wait1Msec(700);
      break;
	   }
	   else
	   {
	     motor[motorA] = 50;                //Motor C is run at a 100 power level
      motor[motorB] = 50;                //motor B is run at a 100 power level
      motor[motorC] = 50;
      motor[motorD] = 50;
	 		}
	 }
	 motor[motorA] = 25;                //Motor C is run at a 100 power level
      motor[motorB] = -25;                //motor B is run at a 100 power level
      motor[motorC] = 25;
      motor[motorD] = -25;
      wait1Msec(100);

      motor[motorA] = 50;                //Motor C is run at a 100 power level
      motor[motorB] = 50;                //motor B is run at a 100 power level
      motor[motorC] = 50;
      motor[motorD] = 50;
      wait1Msec(300);

      if (SensorValue(touchSensor) == 1)
      {
      	motor[motorA] = -50;                //Motor C is run at a 100 power level
      motor[motorB] = -50;                //motor B is run at a 100 power level
      motor[motorC] = -50;
      motor[motorD] = -50;
      wait1Msec
      }
}
