//#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
//#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
//#pragma config(Sensor, S3,     irSeeker,       sensorNone)
//#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
//#pragma config(Motor,  mtr_S1_C1_2,     motorC,        tmotorTetrix, openLoop)
//#pragma config(Motor,  mtr_S1_C2_1,     motorB,        tmotorTetrix, openLoop, reversed)
//#pragma config(Motor,  mtr_S1_C2_2,     motorA,        tmotorTetrix, openLoop)
////*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	 while(SensorValue(touchSensor) == 0)   //a while loop is declared with the touchsensor's value being 0 as it true condition
   {
      motor[motorA] = 50;                //Motor C is run at a 100 power level
      motor[motorB] = 50;                //motor B is run at a 100 power level
      motor[motorC] = 50;
      motor[motorD] = 50;
   }

   motor[motorA] = -50;
   motor[motorC] = -50;                   //Motor C is run at a -75 power level
   motor[motorB] = -50;
   motor[motorD] = -50;										//motor B is run at a -75 power level
   wait1Msec(1000);                       //the program waits 1000 milliseconds before running further code
}
