#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorC,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorB,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorA,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//move forward to thing
	motor[motorA] = 50;
	motor[motorB] = 50;
	motor[motorC] = 50;
	motor[motorD] = 50;
	wait1Msec(1500);

	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	motor[motorD] = 0;
	wait1Msec(200);

	//right quarter turn
	motor[motorA] = 0;
	motor[motorB] = 50;
	motor[motorC] = 0;
	motor[motorD] = 50;
	wait1Msec(850);

	motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	motor[motorD] = 0;
	wait1Msec(200);

	//foward
	motor[motorA] = 50;
	motor[motorB] = 50;
	motor[motorC] = 50;
	motor[motorD] = 50;
	wait1Msec(1000);

		motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	motor[motorD] = 0;
	wait1Msec(200);

	//right quarter turn
	motor[motorA] = -50;
	motor[motorB] = 50;
	motor[motorC] = -50;
	motor[motorD] = 50;
	wait1Msec(425);

		motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	motor[motorD] = 0;
	wait1Msec(200);

	//forward
		motor[motorA] = 50;
	motor[motorB] = 50;
	motor[motorC] = 50;
	motor[motorD] = 50;
	wait1Msec(1000);

		motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	motor[motorD] = 0;
	wait1Msec(200);

	//left quarter turn
	motor[motorA] = 50;
	motor[motorB] = -50;
	motor[motorC] = 50;
	motor[motorD] = -50;
	wait1Msec(425);

		motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	motor[motorD] = 0;
	wait1Msec(200);

	//forward
			motor[motorA] = 50;
	motor[motorB] = 50;
	motor[motorC] = 50;
	motor[motorD] = 50;
	wait1Msec(1000);

		motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	motor[motorD] = 0;
	wait1Msec(200);

	//right quarter turn
		motor[motorA] = 0;
	motor[motorB] = 50;
	motor[motorC] = 0;
	motor[motorD] = 50;
	wait1Msec(850);

			motor[motorA] = 0;
	motor[motorB] = 0;
	motor[motorC] = 0;
	motor[motorD] = 0;
	wait1Msec(200);

	//forward
			motor[motorA] = 50;
	motor[motorB] = 50;
	motor[motorC] = 50;
	motor[motorD] = 50;
	wait1Msec(300);
}
