#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          B,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          C,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		motor[C] = 100;
		motor[B] = 100;
		wait1Msec(10000);

		motor[C] = 0;
		motor[B] = 0;
		wait1Msec(10000);

		motor[C] = -100;
		motor[B] = -100;
		wait1Msec(10000);

	}


}
